#!/bin/bash

### EDIT THESE VALUES #########################################################
APP="/home/ccpa/bin/firefox/.venv/bin/python /home/ccpa/bin/firefox/firefox_wrightenich.py"       # path to real executable
ICON="/home/ccpa/Pictures/conch.png"    	  # icon file - only png supported
WAIT=2                			  # wait time for application window to display - adjust to suit
###############################################################################

###############################################################################
### DON'T CHANGE ANYTHING BELOW
###############################################################################
function change-panel-icon {

    sleep $WAIT
    activeWinLine=$(xprop -root | grep "_NET_ACTIVE_WINDOW(WINDOW)")
    activeWinId="${activeWinLine:40}"

    xseticon -id "$activeWinId" "$ICON"
}

$APP & change-panel-icon
